name: RBniCS tutorials

on:
  schedule:
    - cron: "0 21 * * WED"
  workflow_dispatch:
    inputs:
      required_action:
        description: "Action to run (compare or regold)"
      required_parallelism:
        description: "Parallelism to be employed when running the test (serial, parallel or both)"
      only_on_folder_number:
        description: "Run only on folder number"
      only_on_file_name:
        description: "Run only on file name (without tutorial prefix and extension)"

jobs:
  tutorial:
    if: >-
      (github.event_name == 'schedule' && github.repository == 'RBniCS/RBniCS')
      || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    strategy:
      matrix:
        which: [01/thermal_block, 02/elastic_block, 03/hole, 04/graetz_1, 04/graetz_2,
          05/gaussian_deim, 05/gaussian_eim, 05/gaussian_exact,
          06/thermal_block_unsteady_1_pod, 06/thermal_block_unsteady_1_rb,
          # 06/thermal_block_unsteady_2_pod, 06/thermal_block_unsteady_2_rb,
          # 06/thermal_block_unsteady_3_pod, 06/thermal_block_unsteady_3_rb,
          # 11/quasi_geostrophic,
          12/stokes_1_pod, 12/stokes_1_rb, 12/stokes_2_pod, 12/stokes_2_rb,
          13/elliptic_optimal_control_1_pod, 13/elliptic_optimal_control_1_rb,
          13/elliptic_optimal_control_2_pod, 13/elliptic_optimal_control_2_rb,
          14/stokes_optimal_control_1,
          # 15/quasi_geostrophic_optimal_control,
          17/navier_stokes_exact_1, 17/navier_stokes_exact_2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1  # @v2 cannot be used because container image has old version of git
      - name: Get folder number and file name
        uses: ./.github/actions/tutorials/parse_matrix
        with:
          matrix_which: ${{ matrix.which }}
          folder_name_variable: FOLDER_NUMBER
          file_name_variable: TUTORIAL_NAME
      - name: Get required action (compare or regold) and required parallelism (serial, parallel or both)
        uses: ./.github/actions/tutorials/parse_workflow_dispatch
        with:
          required_action: ${{ github.event.inputs.required_action }}
          required_parallelism: ${{ github.event.inputs.required_parallelism }}
          only_on_folder_name: ${{ github.event.inputs.only_on_folder_number }}
          only_on_file_name: ${{ github.event.inputs.only_on_file_name }}
          current_folder_name: ${{ env.FOLDER_NUMBER }}
          current_file_name: ${{ env.TUTORIAL_NAME }}
      - name: Install RBniCS
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/install
      - name: Clone test data repository
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/test_data/clone
        with:
          branch: master
      - name: Regold tutorials (serial)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "regold"
          pytest: "pytest"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Clean up regolded results (serial)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
      - name: Run tutorials (serial, offline and online)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "pytest"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Run tutorials (serial, online only)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "pytest"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
#      - name: Run tutorials (parallel from serial, online only) - not working due to empty mesh on one process
#        if: >-
#          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
#          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
#        uses: ./.github/actions/tutorials/run_action
#        with:
#          action: "compare"
#          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
#          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
#          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Clean up results (serial)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
      - name: Regold tutorials (parallel)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "regold"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Clean up regolded results (parallel)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
      - name: Run tutorials (parallel, offline and online)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Run tutorials (parallel, online only)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
#      - name: Run tutorials (serial from parallel, online only) - need to mix gold results in the comparison
#        if: >-
#          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
#          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
#        uses: ./.github/actions/tutorials/run_action
#        with:
#          action: "compare"
#          pytest: "pytest"
#          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
#          file_name: "tutorial_${{ env.TUTORIAL_NAME }}.ipynb"
      - name: Clean up results (parallel)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tutorials/${{ env.FOLDER_NUMBER }}*"
      - name: Push regolded test data
        if: env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/test_data/push
        with:
          GIT_USERNAME: ${{ secrets.MIRROR_GITHUB_USER }}
          GIT_PASSWORD: ${{ secrets.MIRROR_GITHUB_TOKEN }}
      - name: Store diffs on failure
        if: (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') && failure()
        uses: actions/upload-artifact@v2
        with:
          name: diff_${{ env.FOLDER_NUMBER }}_${{ env.TUTORIAL_NAME }}
          path: tutorials/${{ env.FOLDER_NUMBER }}*/**/*_diff
